# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: service.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='service.proto',
  package='',
  syntax='proto3',
  serialized_options=b'\n\002pb',
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\rservice.proto\"y\n\x11IMemoryProperties\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x11\n\ttimestamp\x18\x02 \x01(\x02\x12\x12\n\nevaluation\x18\x03 \x01(\x01\x12\t\n\x01I\x18\x04 \x01(\x02\x12$\n\x08memories\x18\x05 \x03(\x0b\x32\x12.IMemoryProperties\"\xb9\x01\n\x12ICodeletProperties\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x12\n\nactivation\x18\x02 \x01(\x01\x12\x11\n\ttimestamp\x18\x03 \x01(\x02\x12%\n\tbroadcast\x18\x04 \x03(\x0b\x32\x12.IMemoryProperties\x12\"\n\x06inputs\x18\x05 \x03(\x0b\x32\x12.IMemoryProperties\x12#\n\x07outputs\x18\x06 \x03(\x0b\x32\x12.IMemoryProperties\"\x1d\n\rjsonRetornado\x12\x0c\n\x04json\x18\x01 \x01(\t\"0\n\x0cresponseInfo\x12 \n\x08response\x18\x01 \x01(\x0b\x32\x0e.jsonRetornado\"Z\n\x0b\x41PIResponse\x12$\n\x08memories\x18\x01 \x03(\x0b\x32\x12.IMemoryProperties\x12%\n\x08\x63odelets\x18\x02 \x03(\x0b\x32\x13.ICodeletProperties\"8\n\x10memoriesResponse\x12$\n\x08memories\x18\x01 \x03(\x0b\x32\x12.IMemoryProperties\"9\n\x10\x63odeletsResponse\x12%\n\x08\x63odelets\x18\x01 \x03(\x0b\x32\x13.ICodeletProperties\"\x1a\n\tindexInfo\x12\r\n\x05index\x18\x01 \x01(\x03\"\x07\n\x05\x45mpty\"\x17\n\x07infoAdd\x12\x0c\n\x04json\x18\x01 \x01(\t\"\x1e\n\nresponseOK\x12\x10\n\x08mensagem\x18\x01 \x01(\t2\x9e\x02\n\x0bgrpcService\x12\x30\n\x16getMemoriesAndCodelets\x12\x06.Empty\x1a\x0c.APIResponse\"\x00\x12*\n\x0bgetMemories\x12\x06.Empty\x1a\x11.memoriesResponse\"\x00\x12*\n\x0bgetCodelets\x12\x06.Empty\x1a\x11.codeletsResponse\"\x00\x12&\n\x07getInfo\x12\n.indexInfo\x1a\r.responseInfo\"\x00\x12\"\n\x07setInfo\x12\x08.infoAdd\x1a\x0b.responseOK\"\x00\x12\x39\n\x0bsendCodelet\x12\x11.codeletsResponse\x1a\x11.codeletsResponse\"\x00(\x01\x30\x01\x42\x04\n\x02pbb\x06proto3'
)




_IMEMORYPROPERTIES = _descriptor.Descriptor(
  name='IMemoryProperties',
  full_name='IMemoryProperties',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='name', full_name='IMemoryProperties.name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='timestamp', full_name='IMemoryProperties.timestamp', index=1,
      number=2, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='evaluation', full_name='IMemoryProperties.evaluation', index=2,
      number=3, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='I', full_name='IMemoryProperties.I', index=3,
      number=4, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='memories', full_name='IMemoryProperties.memories', index=4,
      number=5, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=17,
  serialized_end=138,
)


_ICODELETPROPERTIES = _descriptor.Descriptor(
  name='ICodeletProperties',
  full_name='ICodeletProperties',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='name', full_name='ICodeletProperties.name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='activation', full_name='ICodeletProperties.activation', index=1,
      number=2, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='timestamp', full_name='ICodeletProperties.timestamp', index=2,
      number=3, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='broadcast', full_name='ICodeletProperties.broadcast', index=3,
      number=4, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='inputs', full_name='ICodeletProperties.inputs', index=4,
      number=5, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='outputs', full_name='ICodeletProperties.outputs', index=5,
      number=6, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=141,
  serialized_end=326,
)


_JSONRETORNADO = _descriptor.Descriptor(
  name='jsonRetornado',
  full_name='jsonRetornado',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='json', full_name='jsonRetornado.json', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=328,
  serialized_end=357,
)


_RESPONSEINFO = _descriptor.Descriptor(
  name='responseInfo',
  full_name='responseInfo',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='response', full_name='responseInfo.response', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=359,
  serialized_end=407,
)


_APIRESPONSE = _descriptor.Descriptor(
  name='APIResponse',
  full_name='APIResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='memories', full_name='APIResponse.memories', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='codelets', full_name='APIResponse.codelets', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=409,
  serialized_end=499,
)


_MEMORIESRESPONSE = _descriptor.Descriptor(
  name='memoriesResponse',
  full_name='memoriesResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='memories', full_name='memoriesResponse.memories', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=501,
  serialized_end=557,
)


_CODELETSRESPONSE = _descriptor.Descriptor(
  name='codeletsResponse',
  full_name='codeletsResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='codelets', full_name='codeletsResponse.codelets', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=559,
  serialized_end=616,
)


_INDEXINFO = _descriptor.Descriptor(
  name='indexInfo',
  full_name='indexInfo',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='index', full_name='indexInfo.index', index=0,
      number=1, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=618,
  serialized_end=644,
)


_EMPTY = _descriptor.Descriptor(
  name='Empty',
  full_name='Empty',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=646,
  serialized_end=653,
)


_INFOADD = _descriptor.Descriptor(
  name='infoAdd',
  full_name='infoAdd',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='json', full_name='infoAdd.json', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=655,
  serialized_end=678,
)


_RESPONSEOK = _descriptor.Descriptor(
  name='responseOK',
  full_name='responseOK',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='mensagem', full_name='responseOK.mensagem', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=680,
  serialized_end=710,
)

_IMEMORYPROPERTIES.fields_by_name['memories'].message_type = _IMEMORYPROPERTIES
_ICODELETPROPERTIES.fields_by_name['broadcast'].message_type = _IMEMORYPROPERTIES
_ICODELETPROPERTIES.fields_by_name['inputs'].message_type = _IMEMORYPROPERTIES
_ICODELETPROPERTIES.fields_by_name['outputs'].message_type = _IMEMORYPROPERTIES
_RESPONSEINFO.fields_by_name['response'].message_type = _JSONRETORNADO
_APIRESPONSE.fields_by_name['memories'].message_type = _IMEMORYPROPERTIES
_APIRESPONSE.fields_by_name['codelets'].message_type = _ICODELETPROPERTIES
_MEMORIESRESPONSE.fields_by_name['memories'].message_type = _IMEMORYPROPERTIES
_CODELETSRESPONSE.fields_by_name['codelets'].message_type = _ICODELETPROPERTIES
DESCRIPTOR.message_types_by_name['IMemoryProperties'] = _IMEMORYPROPERTIES
DESCRIPTOR.message_types_by_name['ICodeletProperties'] = _ICODELETPROPERTIES
DESCRIPTOR.message_types_by_name['jsonRetornado'] = _JSONRETORNADO
DESCRIPTOR.message_types_by_name['responseInfo'] = _RESPONSEINFO
DESCRIPTOR.message_types_by_name['APIResponse'] = _APIRESPONSE
DESCRIPTOR.message_types_by_name['memoriesResponse'] = _MEMORIESRESPONSE
DESCRIPTOR.message_types_by_name['codeletsResponse'] = _CODELETSRESPONSE
DESCRIPTOR.message_types_by_name['indexInfo'] = _INDEXINFO
DESCRIPTOR.message_types_by_name['Empty'] = _EMPTY
DESCRIPTOR.message_types_by_name['infoAdd'] = _INFOADD
DESCRIPTOR.message_types_by_name['responseOK'] = _RESPONSEOK
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

IMemoryProperties = _reflection.GeneratedProtocolMessageType('IMemoryProperties', (_message.Message,), {
  'DESCRIPTOR' : _IMEMORYPROPERTIES,
  '__module__' : 'service_pb2'
  # @@protoc_insertion_point(class_scope:IMemoryProperties)
  })
_sym_db.RegisterMessage(IMemoryProperties)

ICodeletProperties = _reflection.GeneratedProtocolMessageType('ICodeletProperties', (_message.Message,), {
  'DESCRIPTOR' : _ICODELETPROPERTIES,
  '__module__' : 'service_pb2'
  # @@protoc_insertion_point(class_scope:ICodeletProperties)
  })
_sym_db.RegisterMessage(ICodeletProperties)

jsonRetornado = _reflection.GeneratedProtocolMessageType('jsonRetornado', (_message.Message,), {
  'DESCRIPTOR' : _JSONRETORNADO,
  '__module__' : 'service_pb2'
  # @@protoc_insertion_point(class_scope:jsonRetornado)
  })
_sym_db.RegisterMessage(jsonRetornado)

responseInfo = _reflection.GeneratedProtocolMessageType('responseInfo', (_message.Message,), {
  'DESCRIPTOR' : _RESPONSEINFO,
  '__module__' : 'service_pb2'
  # @@protoc_insertion_point(class_scope:responseInfo)
  })
_sym_db.RegisterMessage(responseInfo)

APIResponse = _reflection.GeneratedProtocolMessageType('APIResponse', (_message.Message,), {
  'DESCRIPTOR' : _APIRESPONSE,
  '__module__' : 'service_pb2'
  # @@protoc_insertion_point(class_scope:APIResponse)
  })
_sym_db.RegisterMessage(APIResponse)

memoriesResponse = _reflection.GeneratedProtocolMessageType('memoriesResponse', (_message.Message,), {
  'DESCRIPTOR' : _MEMORIESRESPONSE,
  '__module__' : 'service_pb2'
  # @@protoc_insertion_point(class_scope:memoriesResponse)
  })
_sym_db.RegisterMessage(memoriesResponse)

codeletsResponse = _reflection.GeneratedProtocolMessageType('codeletsResponse', (_message.Message,), {
  'DESCRIPTOR' : _CODELETSRESPONSE,
  '__module__' : 'service_pb2'
  # @@protoc_insertion_point(class_scope:codeletsResponse)
  })
_sym_db.RegisterMessage(codeletsResponse)

indexInfo = _reflection.GeneratedProtocolMessageType('indexInfo', (_message.Message,), {
  'DESCRIPTOR' : _INDEXINFO,
  '__module__' : 'service_pb2'
  # @@protoc_insertion_point(class_scope:indexInfo)
  })
_sym_db.RegisterMessage(indexInfo)

Empty = _reflection.GeneratedProtocolMessageType('Empty', (_message.Message,), {
  'DESCRIPTOR' : _EMPTY,
  '__module__' : 'service_pb2'
  # @@protoc_insertion_point(class_scope:Empty)
  })
_sym_db.RegisterMessage(Empty)

infoAdd = _reflection.GeneratedProtocolMessageType('infoAdd', (_message.Message,), {
  'DESCRIPTOR' : _INFOADD,
  '__module__' : 'service_pb2'
  # @@protoc_insertion_point(class_scope:infoAdd)
  })
_sym_db.RegisterMessage(infoAdd)

responseOK = _reflection.GeneratedProtocolMessageType('responseOK', (_message.Message,), {
  'DESCRIPTOR' : _RESPONSEOK,
  '__module__' : 'service_pb2'
  # @@protoc_insertion_point(class_scope:responseOK)
  })
_sym_db.RegisterMessage(responseOK)


DESCRIPTOR._options = None

_GRPCSERVICE = _descriptor.ServiceDescriptor(
  name='grpcService',
  full_name='grpcService',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=713,
  serialized_end=999,
  methods=[
  _descriptor.MethodDescriptor(
    name='getMemoriesAndCodelets',
    full_name='grpcService.getMemoriesAndCodelets',
    index=0,
    containing_service=None,
    input_type=_EMPTY,
    output_type=_APIRESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='getMemories',
    full_name='grpcService.getMemories',
    index=1,
    containing_service=None,
    input_type=_EMPTY,
    output_type=_MEMORIESRESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='getCodelets',
    full_name='grpcService.getCodelets',
    index=2,
    containing_service=None,
    input_type=_EMPTY,
    output_type=_CODELETSRESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='getInfo',
    full_name='grpcService.getInfo',
    index=3,
    containing_service=None,
    input_type=_INDEXINFO,
    output_type=_RESPONSEINFO,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='setInfo',
    full_name='grpcService.setInfo',
    index=4,
    containing_service=None,
    input_type=_INFOADD,
    output_type=_RESPONSEOK,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='sendCodelet',
    full_name='grpcService.sendCodelet',
    index=5,
    containing_service=None,
    input_type=_CODELETSRESPONSE,
    output_type=_CODELETSRESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_GRPCSERVICE)

DESCRIPTOR.services_by_name['grpcService'] = _GRPCSERVICE

# @@protoc_insertion_point(module_scope)
